### ISSUE TITLE
Guia de estilo - Nomes (URLs slugs) das organizações no CKAN

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/issues#14]
Vamos utilizar o padrão `nome-sigla` para a URL slug para que seja mais informativo que a `sigla` e mais conveniente de inserir no CKAN do que o `nome`, tendo em vista que o nome da organização será "Nome - SIGLA"

**Comment by fjuniorr** [comment]
Os nomes das organizações existentes hoje são

- `organization/fundacao-de-amparo-a-pesquisa-do-estado-de-minas-gerais`
- `organization/controladoria-geral-do-estado-cge`
- `organization/secretaria-de-estado-planejamento-e-gestao`
- `organization/secretaria-de-estado-de-saude`

Indicando um padrão, come exceção da CGE, de utilizar o nome completo da instituição.

As alternativas que podemos utilizar são:

- `nome-sigla`
- `nome`
- `sigla`
- `dominio`

Abaixo algumas considerações sobre as alternativas.

## nome e nome-sigla

Apesar de informativo (não pressupõe saber o significado da SIGLA), acho o uso do `nome` longo demais. 

## dominio

A utilização dos domínios dos sites oficiais dos órgãos pode gerar problemas pois

1. Um orgao pode ter multiplos dominios (eg. http://www.infraestrutura.mg.gov.br/, http://www.transportes.mg.gov.br/, http://www.setop.mg.gov.br/)
1. O dominio pode fazer referência a política pública (eg. transportes), sem abranger todos os conjuntos de dados respectivos (eg. DER)
1. Alguns órgãos podem não possuir site

## Observações gerais

- O [governo federal](http://dados.gov.br/) usa a convenção de `nome-sigla`

- Importante saber quais campos a [busca por organização](http://dados.mg.gov.br/organization) utiliza para possibilitar busca por nome e sigla, ainda que isso não apareça na URL

**Comment by fjuniorr** [comment]
Duas informações relevantes para a decisão. 

1. A busca por organização utiliza os campos nome e organização para retornar os resultados

    ![Organizações_-_Dados_Abertos_MG](https://user-images.githubusercontent.com/4969445/87660922-333cb780-c736-11ea-90e9-8620a3628f9f.png)

1. Na criação de uma nova organização a slug da URL é gerada por default a partir do nome da organização

    ![image](https://user-images.githubusercontent.com/4969445/87661075-6717dd00-c736-11ea-8b77-1830a10f4a40.png)

**Comment by kesiabomfa** [comment]
Eu sou a favor do nome completo da instituição. Siglas podem ter nomes curtos, mas uma sigla, sozinha, pode confundir o usuário.

**Comment by silviana-faria** [comment]
Eu sou a favor do nome-sigla. Nesse sentido a busca será possível por 2 critérios.

* organization/controladoria-geral-do-estado-cge

**Comment by fjuniorr** [comment]
> Eu sou a favor do nome-sigla. Nesse sentido a busca será possível por 2 critérios.
> 
> * organization/controladoria-geral-do-estado-cge

A [busca vai funcionar](https://github.com/dados-mg/issues/issues/14#issuecomment-659325113) por nome completo e sigla do órgão desde que a gente coloque essa informação no campo nome.

Ou seja, não precisamos de inserir isso na URL para ofertar a funcionalidade de busca, que considero essencial.

**Comment by silviana-faria** [comment]
Entendi.
Então sou a favor do nome completo na url.
