### ISSUE TITLE
Separador de Linhas no Meio do CSV – POWER BI

### ISSUE THREAD

**Issue by kesiabomfa** [dados-mg/issues#24]

**Comment by kesiabomfa** [comment]
**SOLUÇÃO**  
**_Clique:_**
1.	Arquivo
2.	Opções e Configurações
3.	Configurações da Fonte de Dados
4.	Selecione o arquivo desejado
5.	Alterar Fonte
6.	Em Quebra de linhas selecione: “Ignorar quebra de linhas entre aspas”
7.	Ok
8.	Fechar em Obter 

**RELATO DO PROBLEMA**

Na carga do arquivo CSV de contratações-emergenciais-covid-19 ocorreu um problema na leitura dos dados ocasionados por uma situação gerada no banco de dados original – ARMAZÉM BO.

No momento da descrição do objeto, o operador utilizou um elemento de nova linha na descrição do objeto, ocasionando no CSV a interpretação de uma nova linha.

Essa situação já tinha sido relatada, mas ficou evidente quando da transferência dos dados para o Power BI, que evidenciou a existência de mais linhas do que no arquivo original, refletindo em distorções no número de processos de compras e erro na soma do valor total homologado.

Para resolver esse problema foi utilizado uma solução do próprio power BI que ignora a linhas entre as aspas. [Vide solução](https://community.powerbi.com/t5/Desktop/ignoring-Line-breaks-within-quotes-while-importing-folder/td-p/234540)

Erro: Outras informações aparecem na Coluna de Número do Processo
![](static/powerbi.png)

**Comment by fjuniorr** [comment]
Um dos padrões para formatação de arquivos CSV é a [RFC 4180](https://tools.ietf.org/html/rfc4180). Ela estabelece que 

> 6. Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes. For example:
> 
> ```
> "aaa","b CRLF
> bb","ccc" CRLF
> zzz,yyy,xxx
> ```

__Pra mim a conclusão é que o comportamento default do PowerBI deveria ser outro. Como é uma ferramenta muito utilizada, é um ótimo conteúdo para nosso material de treinamento.__

Em governos essa interpretação é mais forte ainda, já que nos [Padrões de Interoperabilidade de Governo Eletrônico - ePING](http://eping.governoeletronico.gov.br/) "Arquivos do tipo “banco de dados” para estações de trabalho" a RFC 4180 consta como padrão adotado. De acordo com a e-PING

> Adotado (A): item adotado pelo governo como padrão na arquitetura ePING, tendo sido submetido a um processo formal de homologação realizado por parte de uma instituição do governo ou por uma outra instituição com delegação formal para realizar o processo. Também é considerado homologado quando baseado em uma proposição devidamente fundamentada pela coordenação do segmento, publicada no sítio e aprovado pela Coordenação da ePING. Os componentes com padrão nível Adotado devem ser obrigatoriamente adotados em novos produtos/projetos de TI;
