### ISSUE TITLE
Testes de situações que podem gerar mudança na codificação do upload Compras Emergenciais

### ISSUE THREAD

**Issue by kesiabomfa** [dados-mg/issues#25]

**Comment by kesiabomfa** [comment]
**SITUAÇÃO**

Em algumas cargas identificou-se a mudança da codificação dos dados CSV de UTF-8 para WIN1252.
Para identificar as situações que podem gerar essa mudança, realizou-se uma série de testes na data de 10/08/2020 com a simulação das possíveis rotinas antes do upload. Os testes foram realizados no ATOM.

**TESTES 

### Teste 1
Abrir o arquivo no EXCEL, salvar em CSV e subir o arquivo no Dados MG:
- Codificação do arquivo antes de abrir no EXCEL: UTF-8
- Codificação do arquivo após salvar em "CSV (separado por vírgulas)": UTF-8
- Codificação do arquivo após o upload no dados.mg: UTF-8


### Teste 2
Abrir e fechar o arquivo no EXCEL e subir o arquivo no Dados MG:
- Codificação do arquivo antes de abrir no EXCEL: UTF-8
- Codificação do arquivo após fechar no EXCEL: UTF-8
- Codificação do arquivo após o upload no dados.mg: UTF-8

### Teste 3
Copiar e colar o arquivo em outra pasta e subir o arquivo no Dados MG:
- Codificação do arquivo antes de copiar: UTF-8
- Codificação do arquivo após colar: UTF-8
- Codificação do arquivo após o upload no dados.mg: UTF-8

Não foram encontrados erros em nenhum desses procedimentos.

**Comment by fjuniorr** [comment]
@kesiabomfa como não foi possível reproduzir esse erro também estou fechando esse issue.
