### ISSUE TITLE
Recuperação de senha

### ISSUE THREAD

**Issue by silviana-faria** [dados-mg/issues#29]

**Comment by silviana-faria** [comment]
A recuperação de senha tanto no ambiente de [homologação](http://10.183.67.30/user/reset) quanto no ambiente de [produção](http://dados.mg.gov.br/user/reset) apresenta erro.

#### Produção

![image](https://user-images.githubusercontent.com/53793354/90125989-5197d200-dd39-11ea-9f8b-7359814ebbdf.png)

#### Homologação

![image](https://user-images.githubusercontent.com/53793354/90126305-d5ea5500-dd39-11ea-844f-fb11d2f39fb0.png)

**Comment by fjuniorr** [comment]
Problema solucionado
