### ISSUE TITLE
Pré-visualização dos dados - Datastore

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/issues#4]
Determinar necessidade de instalação e configuração de:

* [ ] [DataPusher](https://docs.ckan.org/projects/datapusher/en/latest/)
* [ ] [FileStore](https://docs.ckan.org/en/2.8/maintaining/filestore.html)

Pesquisar funcionalidades do DataStore de:

* [ ] [Data dictionary](https://docs.ckan.org/en/2.8/maintaining/datastore.html#data-dictionary) 
* [ ] [DataStore API](https://docs.ckan.org/en/2.8/maintaining/datastore.html#the-datastore-api)

**Comment by fjuniorr** [comment]
A conclusão da discussão em #3 é de que não devemos utilizar o [DataProxy](https://github.com/okfn/dataproxy) como forma de viabilizar a pré-visualização de dados. 

Essa recomendação existe tanto na [comunidade](https://github.com/ckan/ideas/issues/217) quanto na [documentação oficial](https://docs.ckan.org/en/2.8/maintaining/data-viewer.html#data-explorer) que afirma

> Support for the DataProxy will be dropped on future CKAN releases

Esse ticket é para decidirmos sobre como vamos viabilizar a pré-visualização, que, não somente é uma [melhor prática reconhecida pela W3C](https://w3c.github.io/dwbp/bp.html#ProvideComplementaryPresentations), mas se provou essencial no caso concreto de divulgação das [contratações emergenciais para combate ao COVID-19](http://cge.mg.gov.br/noticias-artigos/724-o-portal-da-transparencia-de-mg-disponibiliza-para-a-consulta-e-controle-social-dos-cidadaos-e-cidadas-todas-as-contratacoes-emergenciais-destinadas-ao-enfrentamento-do-covid-19-no-estado).

A forma recomendada de prover pré-visualização é a utilização da extensão [DataStore](https://docs.ckan.org/en/2.8/maintaining/datastore.html). No README do DataProxy temos

> Note for CKAN users: The DataProxy is not actively maintained. Users looking for a structured API for tabular data and robust visualizations should use the CKAN DataStore

**Comment by Andrelamor** [comment]
## Ver [Preenchimento automático do Dicionário de dados do datastore #9](https://github.com/dados-mg/issues/issues/9)
