### ISSUE TITLE
filtro de busca por dataset não funciona

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/issues#64]
![image](https://user-images.githubusercontent.com/52294411/148438556-e1e66d74-4981-4fb5-81f9-545cd6101515.png)
![image](https://user-images.githubusercontent.com/52294411/148438366-86abf925-9757-4a05-9b66-0057fc0ed33e.png)
![image](https://user-images.githubusercontent.com/52294411/148438422-9784e3e0-fe41-43a3-a5a4-bdeb37405419.png)

**Comment by Andrelamor** [comment]
![image](https://user-images.githubusercontent.com/52294411/148560016-5dd9e73d-7a3a-4e05-ba7b-f14cf20a4027.png)

![image](https://user-images.githubusercontent.com/52294411/148560119-7ecd7412-b7e7-479c-9db0-ff8c11f464ee.png)

**Comment by fjuniorr** [comment]
Pela [documentação](https://docs.ckan.org/en/2.9/user-guide.html#search-in-detail) fico com a impressão que esse resultado é o comportamento esperado

> CKAN will search for the complete word and when doing simple search are wildcards are not supported.

**Comment by Andrelamor** [comment]
de fato, ele só aceita meias-palavras ou * se tiver uma expressão de busca avançada (p. ex., `title`): 
![image](https://user-images.githubusercontent.com/52294411/148688398-3ba7a7bc-8647-4a16-89a1-7badb699e695.png)
![image](https://user-images.githubusercontent.com/52294411/148688313-c104d5ad-40ba-46a5-82fe-e8eaf0732514.png)

**Comment by Andrelamor** [comment]
na página 13 do [guia do usuário](file:///C:/Users/Andre/Documents/teletrabalho/Guia%20de%20Referencia%20para%20Uso%20Cidadao%20-%202021v2.pdf), há orientação para digitação de uma palavra inteira, mas não há o alerta sobre a necessidade de digitá-la por completo, sob o risco de parte dela não ser encontrada
