### ISSUE TITLE
Falta vincular o código UA gtags ao site - etiqueta não funciona e analytics não recebe hits

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/issues#7]
No menu superior à esquerda, quando se clica em qq opção de 'relatórios em tempo real', não aparece nenhuma visualização, mesmo quando se está logado no novo domínio dados.mg.gov.br![image](https://user-images.githubusercontent.com/52294411/85320488-85711c80-b499-11ea-9e30-7065c9882984.png)

Na parte de notificações, há a msg de que o domínio de que a propriedade não está recebendo hits
![image](https://user-images.githubusercontent.com/52294411/85320642-c36e4080-b499-11ea-98ea-df0f22ce8f2e.png)

[Configure a etiqueta do Analytics](https://support.google.com/analytics/answer/1008080/?hl=pt&authuser=1)
Neste artigo:
Instruções básicas
Verifique se a etiqueta está a funcionar
Recurso relacionado
Instruções básicas
Se ainda não o fez, crie uma propriedade no Google Analytics. Crie uma propriedade no Analytics para cada Website para o qual pretenda recolher dados. A criação de uma propriedade gera um ID do Google Analytics, que vai utilizar na instalação da gtag.js.
Localize o seu ID do Google Analytics, conforme descrito abaixo. Vai utilizar este ID do Google Analytics na configuração.
Copie e cole a etiqueta global do site em cada página Web que pretenda medir. Adicione a etiqueta imediatamente após a etiqueta de abertura <head> em cada página.

![image](https://user-images.githubusercontent.com/52294411/85321415-067ce380-b49b-11ea-94c1-5a0c00e29622.png)

**Comment by fjuniorr** [comment]
Novamente com a mudança dos ambientes do CKAN o google analytics não está recebendo hits.

O tracking code inserido nas páginas parece estar errado:

<img width="670" alt="view-source_dados_mg_gov_br_dataset" src="https://user-images.githubusercontent.com/4969445/88689648-1fe40180-d0d1-11ea-909a-0925c2b887ae.png">

**Comment by Andrelamor** [comment]
ver Issue 21 https://github.com/dados-mg/issues/issues/21
